# Generated by Django 3.2.6 on 2021-08-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lastt_name',
            new_name='last_name',
        ),
    ]
